### ISSUE TITLE
loss of favorite build

### ISSUE THREAD

**Issue by Y4XH0G** [atomicptr/dauntless-builder-reforged#149] opened 2020-05-05 12:11 UTC
### Summary
i select some build on the site but when i set them to favorites they disppear when i close firefox
https://www.dauntless-builder.ovh/

### Reproduction
1) find a build
2) set it to favorite
3) close firefox
4)go to "my build"
5) no build

ps I'm not english, I use google trad sorry if there is any mistake.

**Comment by atomicptr** [comment] 2020-05-05 12:16
Hey,

I can't help you with dauntless-builder.**ovh**, but maybe you tried to save a build there and then open it on dauntless-builder.**com**?

**Comment by Y4XH0G** [comment] 2020-05-05 12:40
No i  have checked that.
And on builder.com i haven't find some armor build just for the weapon

**Comment by atomicptr** [comment] 2020-05-05 12:44
> No i have checked that.

Hm, after saving the build can you open the browser console (Ctrl + Shift + I) and enter 

```js
localStorage.__db_favorites
```

and give me the result, also same after re-opening the browser. Maybe your browser isn't storing local storage for some reason :thinking:

>  And on builder.com i haven't find some armor build just for the weapon

I sadly don't know what you're trying to say, you can't find some items?

**Comment by Y4XH0G** [comment] 2020-05-05 14:02
I don't know why but now it's working. The build are saved even if i close the browser or restart my computer.

the command show the test build i made ( browser not closed)
after closing the browser the same code line appear.
apparently the browser is storing local storage

I couldn't find armor set on builder.com. I have change the .ovh into .com and it bring me on an other site (not https://www.dauntless-builder.com/) which propose only weapon build 

thank you for your time atomicptr

**Comment by atomicptr** [comment] 2020-05-05 14:15
> 
> 
> I don't know why but now it's working. The build are saved even if i close the browser or restart my computer.
> 
> the command show the test build i made ( browser not closed)
> after closing the browser the same code line appear.
> apparently the browser is storing local storage

:+1:

> I couldn't find armor set on builder.com. I have change the .ovh into .com and it bring me on an other site (not https://www.dauntless-builder.com/) which propose only weapon build

Which one? I can't help with the .ovh one because thats a fork of .com (which is mine).

> thank you for your time atomicptr

np :)

**Comment by Y4XH0G** [comment] 2020-05-05 14:20
> Which one? I can't help with the .ovh one because thats a fork of .com (which is mine).
>
It's on the .ovh

**Comment by atomicptr** [comment] 2020-05-05 14:21
> 
> 
> > Which one? I can't help with the .ovh one because thats a fork of .com (which is mine).
> 
> It's on the .ovh

A favorite build? I thought you meant some data is missing :).

**Comment by atomicptr** [comment] 2020-09-27 13:51
I'll close this since it seems to be either unrelated or not reproducable.

**Closed as completed by atomicptr** 2020-09-27 13:51 UTC

**Comment by Y4XH0G** [comment] 2020-09-27 13:57
Ok
